spring.application.name=notification-service
server.port=8085

# PostgreSQL configuration
# notification-service stores simple notification records in notificationdb.
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:notificationdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:food_user}
spring.datasource.password=${DB_PASSWORD:food_password}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.open-in-view=false

# Kafka configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.vm.notificationservice.dto
spring.kafka.consumer.properties.spring.json.value.default.type=com.vm.notificationservice.dto.OrderPlacedEvent

app.kafka.order-placed-topic=${ORDER_PLACED_TOPIC:order-placed}
